### ISSUE TITLE
Can't switch bookmark style

### ISSUE THREAD

**Issue by Alezy80** [datguysheepy/simple-start#20]
Selection of Compact / Thumbnails / List View is unavailable. And there are no icons for the styles, only color placeholders.

**Comment by datguysheepy** [comment]
Oh yeah, thanks for the head-ups.
I used as a way to showcase what is coming in future updates for Simple Start, but now, when I'm looking at it - you're right it doesn't look good and can be a little misleading.

For now I will just create small bug fix to completely remove this section from settings menu and just redo do it when more bookmarks styles will be added somewhere in the future.

**Comment by datguysheepy** [comment]
fixed in v1.0.5
